"use strict";

const list_of_idioms = `A BACKSEAT DRIVER
A BALANCING/JUGGLING ACT
A BALL OF FIRE
A BLOT ON SB'S CHARACTER
A BRAINBOX
A BREEZE
A BRIGHT SPARK
A BROWN STUDY
A BRUSH WITH FAME
A BUGBEAR
A CAN OF WORMS
A CASTLE IN THE AIR
A CAT GOT ONE'S TONGUE
A CHINK IN THE ARMOUR
A CLEVER DICK
A COLD FISH
A DAYLIGHT ROBBERY
A DEAD END
A DEAD HAND OF
A DEAFENING SILENCE
A DIME A DOZEN
A DOWNWARD SPIRAL
A FAIR CRACK AT THE WHIP
A FAR CRY FROM
A FAUX PASS
A FEATHER IN ONE'S CAP
A FISH OUT OF WATER
A FISH TALE
A FLASH IN THE PAN
A FLY IN THE OINTMENT
A FOOL AND SB'S MONEY ARE SOON PARTED
A FOOL'S ERRAND
A FUDDY DUDDY
A GO-GETTER
A HAPPY CAMPER
A HELPING HAND
A HIVE ACTIVITY
A HOUSEHOLD NAME
A HUSTLE AND BUSTLE
A JUGGLING ACT
A KING'S RANSOM
A KNOW-IT-ALL
A LIE HAS NO LEGS
A LIFELINE
A LIGHT AT THE END OF THE TUNNEL
A LITTLE BIRD TOLD ME
A LIVE WIRE
A LONG FACE
A MAGIC TOUCH
A MISERY GUTS
A MIXED BLESSING
A NEEDLE IN A HAYSTACK
A NIGHT OWL
A PACK OF LIES
A PAIN IN THE ARSE/BACKSIDE
A PAIN IN THE NECK
A PANDORA'S BOX
A PARTY ANIMAL
A PARTY POOPER
A PENNY FOR SB'S THOUGHTS
A PENNY SAVED IS A PENNY EARNED
A PEOPLE PERSON
A PIECE OF CAKE
A PIPE DREAM
A PLUM IN ONE'S MOUTH
A QUESTION MARK OVER
A RIP-OFF
A ROARING SUCCESS
A SHOT IN THE ARM
A SLEDGE HAMMER TO CRACK A NUT
A SMART ALEC
A SMART APPLE
A SMART COOKIE
A SMARTY PANTS
A STICK-IN-THE-MUD
A STORM IN A TEACUP
A STUMBLING BLOCK
A TISSUE OF LIES
A VICIOUS CIRCLE
A VICTORY FOR COMMON SENSE
A WALK IN THE PARK
A WEAK SPOT
A WHITE KNIGHT
A WHITE LIE
A WHIZZ-KID
A WISE GUY
A WOLF IN SHEEP'S CLOTHING
A WORD IN ONE'S EAR
A WORLD OF DIFFERENCE
ABOUT-FACE
ABOUT-TURN
ABSENCE MAKES THE HEART GROW FONDER
ACHILLES HEEL
ACT SB'S AGE
ACT/PLAY THE FOOL
ACTIONS SPEAK LOUDER THAN WORDS
ADD FUEL TO FIRE
ADD INSULT TO INJURY
AIRS AND GRACES
AIRY-FAIRY
ALIVE AND WELL/KICKING
ALL THE BELLS AND WHISTLES
ALL WORK AND NO PLAY MAKES JACK A DULL BOY
AN ACE UP ONE'S SLEEVE
AN APPLE A DAY KEEPS THE DOCTOR AWAY
AN ARMACHAIR CRITIC
AN AWKWARD CUSTOMER
AN EAGER BEAVER
AN EARLY BIRD
AN IRON HAND/FIST IN A VELVET GLOVE
AN UNKNOWN QUANTITY
AN UPHILL BATTLE/STRUGGLE/FIGHT
ANYBODY WHO IS ANYBODY
AS CALM AS A TOAD IN THE SUN
AS COLD AS STONE
AS COOL AS A CUCUMBER
AS DULL AS A DITCHWATER
AS FIT AS A FIDDLE
AS FREE AS A BIRD
AS IF ONE OWNED THE PLACE
AS KEEN AS MUSTARD
AS MAD AS A HORNET
AS NUTTY AS A FRUITCAKE
AS RIGHT AS RAIN
AS SLOW AS THE MOLASSES
AS SLY AS A FOX
AS SMART AS A WHIP
AS SOUND AS A BELL
AS SOUND AS A DOLLAR
AT A CROSSROADS
AT ODDS
AT ONE'S WITS END
AT THE CRACK OF DAWN
AT THE EDGE OF ONE'S SEAT
AT THE END OF ONE'S TETHER
AVANT-GARDE
AVERAGE JOE BLOGGS
AVOID STH LIKE THE PLAGUE
BAD BLOOD
BANG ONE'S HEAD AGAINST A BRICK WALL
BARE ONE'S SOUL
BARK UP THE WRONG TREE
BAT A THOUSAND
BE (CAUGHT) BETWEEN A ROCK AND A HARD PLACE
BE (RIGHT) ON THE MONEY
BE A (NASTY) PIECE OF WORK
BE A BAD EGG
BE A BLESSING IN DISGUISE
BE A CASH COW
BE A DARK HORSE
BE A DEVIL IN DISGUISE
BE A DIPSTICK
BE A DOG'S BREAKFAST
BE A FIGURE OF FUN
BE A FORGEONE CONCLUSION
BE A GOOD EGG
BE A GOODY-GOODY
BE A HARD ACT TO FOLLOW
BE A HARD GOING
BE A HARD/TOUGH NUT
BE A HIGH-FLYER
BE A JACK OF ALL TRADES (MASTER OF NONE)
BE A LAMEBRAIN
BE A LAUGHING STOCK
BE A LEAP IN THE DARK
BE A LONE WOLF
BE A LOUD MOUTH
BE A MAN/WOMAN OF HIS/HER WORD
BE A MONEY SPINNER
BE A NE'ER-DO-WELL
BE A PILLAR OF SOCIETY
BE A SAFE BET
BE A SCAPEGOAT
BE A SHINING EXAMPLE
BE A SHRINKING VIOLET
BE A SLIMEBALL
BE A SNOWFLAKE
BE A SOCIAL BUTTERFLY
BE A STRAIGHT ARROW
BE A WOLF IN SHEEP'S CLOTHING
BE AFRIAD OF ONE'S OWN SHADOW
BE AFTER SB'S BLOOD
BE AHEAD OF THE TIMES
BE ALL GREEK TO SB
BE ALL MOUTH AND NO TROUSERS
BE ALL SWEETNESS AND LIGHT
BE ALL TALK NO ACTION
BE ALL WET
BE AN ACT OF GOD
BE AN APOLOGY FOR
BE AN OPEN BOOK
BE AS BRIGHT AS A BUTTON
BE AS BUSY AS A BEE/BEAVER
BE AS CLEAR AS DAY
BE AS DAFT AS A BRUSH
BE AS DUMB AS A BOX OF ROCKS
BE AS DUMB AS A POST
BE AS GOOD AS ONE'S WORD
BE AS HARD AS NAILS
BE AS HIGH AS A KITE
BE AS MAD AS A BOX OF FROGS
BE AS MAD AS A HATTER
BE AS PLAIN AS THE NOSE ON ONE'S FACE
BE AS RARE AS HEN'S TEETH
BE AS SHARP AS A RAZOR
BE AS SHARP AS A TACK
BE AS SICK AS A DOG
BE AS SILENT AS THE DEAD
BE AS SILENT AS THE GRAVE
BE AS SOBER AS A JUDGE
BE AS STRAIGHT AS A DIE
BE AT A LOSS FOR WORDS
BE AT DEATH'S DOOR
BE AT EACH OTHER'S THROATS
BE AT LOGGERHEADS WITH SB
BE AT SB'S BECK AND CALL
BE AT SB'S MERCY
BE AT THE BOTTOM OF THE CAREER LADDER
BE AT THE TOP OF ONE'S GAME
BE BACK IN ACTION
BE BAD/TOUGH LUCK
BE BANG ON
BE BEHIND THE TIMES
BE BENEATH THE RADAR
BE BENT OUT OF SHAPE
BE BONE IDLE
BE BOTTOM SHELF
BE BRAIN DEAD
BE BRIGHT-EYED AND BUSHY-TAILED
BE BROUGHT/CALLED TO ACCOUNT
BE CAST IN THE SAME MOULD
BE CHEAP AND CHEERFUL
BE CHEAP AND NASTY
BE CLEAR AS MUD
BE COOL, CALM, COLLECTED
BE DANICNG IN THE STREETS
BE DEAD ON ONE'S FEET
BE DEAD TIRED
BE DIRT CHEAP
BE DOUBLE-FACED
BE DOWN AND OUT
BE DOWN IN THE MOUTH/DUMPS
BE DOWN ON ONE'S LUCK
BE ECONOMICAL WITH THE TRUTH
BE FAIR AND SQUARE
BE FED UP (TO THE BACK TEETH) WITH
BE FEW AND FAR BETWEEN
BE FLAT BROKE
BE FLOATING/WALKING ON AIR
BE FLUSH FOR CASH
BE FOAMING AT THE MOUTH
BE FREE AND CLEAR
BE FULL OF THE JOYS OF SPRING
BE GOOD-FOR-NOTHING
BE GREEN WITH ENVY
BE HEAD AND SHOULDERS ABOVE
BE HIGH ON LIFE
BE HIT WITH SB
BE HOPPING MAD
BE HOT UNDER COLLAR
BE IN A FUNK
BE IN A JAM
BE IN A PICKLE
BE IN A SPIN
BE IN A STEW
BE IN ARREARS
BE IN LINE FOR STH
BE IN LUCK
BE IN ONE'S ELEMENT
BE IN ONE'S RIGHT MIND
BE IN SB'S GOOD BOOKS
BE IN SEVENTH HEAVEN
BE IN STITCHES
BE IN STORE
BE IN THE BACK BURNER
BE IN THE BLACK
BE IN THE DARK
BE IN THE DRIVING SEAT
BE IN THE GROOVE
BE IN THE HOLE
BE IN THE KNOW
BE IN THE MONEY
BE IN THE PIPELINE
BE IN THE PUBLIC EYE
BE IN THE RED
BE IN THE WARS
BE IN TWO MINDS
BE JUMPING UP AND DOWN
BE JUST TALK
BE KNOCKED DOWN WITH A FEATHER
BE LAUGHING ALL THE WAY TO THE BANK
BE LEAN AND HUNGRY
BE LIKE A GHOST TOWN
BE LIKE CHALK AND CHEESE
BE LIKE FEEDING TIME AT THE ZOO
BE LIKE GETTING THE BLOOD OUT OF A STONE
BE LIKE GOLD DUST
BE LIKE PISSING IN THE WIND
BE LIKE PULLING TEETH
BE LIKE TWO PEAS IN A POD
BE LIKE WATER OF OFF A DUCK'S BACK
BE LOST FOR WORDS
BE MADE OF MONEY
BE MADE OF STERNER STUFF
BE NINE DAYS' WONDER
BE NO BIG DEAL
BE NO CHOIR BOY
BE NO JOKE
BE NO LAUGHING MATTER
BE NOT ALL HERE
BE NOT RIGHT IN THE HEAD
BE OF SERVICE
BE OF SOUND MIND
BE OFF ONE'S FACE
BE OFF ONE'S ROCKER
BE OFF ONE'S TROLLEY
BE OFF THE HOOK
BE ON CLOUD NINE
BE ON ONE'S LAST LEGS
BE ON SB'S BACK
BE ON SPEAKING TERMS
BE ON THE CARDS
BE ON THE MAKE
BE ON THE MEND
BE ON THE ROAD TO RECOVERY
BE ON THE SAFE SIDE
BE ON THE SAME WAVELENGTH
BE ONE SANDWICH SHORT OF A PICNIC
BE OUT FOR BLOOD
BE OUT OF ACTION
BE OUT OF LUCK
BE OUT OF ONE'S ELEMENT
BE OUT OF QUESTION
BE OUT OF SB'S DEPTH
BE OUT OF SORTS
BE OUT OF THIS WORLD
BE OUT-AND-OUT
BE OVER A BARREL
BE OVER THE MOON
BE POLAR OPPOSITES
BE POLES APART
BE QUAKING/SHAKING IN ONE'S BOOTS
BE QUIDS IN
BE RIGHT UP ONE'S ALLEY/STREET
BE ROLLING IN MONEY
BE ROOTED TO THE SPOT
BE ROUND THE BEND
BE RUNNING ON EMPTY
BE RUSHED OFF ONE'S FEET
BE SB'S CUP OF TEA
BE SB'S FORTE
BE SB'S STRONG SUIT
BE SCARED STIFF
BE SCARED TO DEATH
BE SECOND TO NONE
BE SET IN STONE
BE SICK AND TIRED OF
BE SICK TO ONE'S STOMACH
BE SIX FEET UNDER
BE SMOKE AND MIRRORS
BE SMOOTH SAILING
BE SNOWED UNDER
BE SOFT IN THE HEAD
BE STINKING RICH
BE STONE-COLD SOBER
BE STRAPPED FOR CASH
BE STREETS AHEAD
BE STUBBORN AS A MULE
BE STUCK IN THE OLD WAYS
BE TAILOR-MADE
BE THE APPLE OF SB'S EYE
BE THE BEST THING SINCE SLICED BREAD
BE THE BEST/GREATEST THING SINCE SLICED BREAD
BE THE BLACK SHEEP
BE THE BREADWINNER
BE THE CAT'S WHISKERS
BE THE MIRROR IMAGE OF
BE THE ODD ONE OUT
BE THE REAL DEAL
BE THE SALT OF THE EARTH
BE THRILLED TO BITS
BE TICKLED PINK
BE TOFEE NOSED
BE TOO CLEVER BY HALVES
BE TOP DRAWER
BE TOP NOTCH
BE UNDER-THE-RADAR
BE UP IN ARMS
BE UP IN THE AIR
BE UP TO DATE
BE UP TO ONE'S EYES/EARS IN
BE UP TO SPEED ON
BE UP TO THE MARK
BE UP WITH THE LARK
BE WELL-HEELED
BE WELL-OFF
BE WORLDS APART
BE YELLOW
BEAR A GRUDGE
BEAR IN MIND
BEAR STH IN MIND
BEAT AROUND THE BUSH
BEAT ONE'S GUMS
BEAT THE RAP
BECOME LAW UNTO ONESELF
BEND ONE'S EAR
BEND THE RULES
BEND THE RULES/LAW
BEND THE TRUTH
BET THE FARM ON STH
BETTER SAFE THAN SORRY
BETWEEN THE DEVIL AND THE DEEP BLUE SEA
BIG CHEESE
BIG GUN
BIG NAME
BIG SHOT
BIRDS OF A FEATHER (FLOCK TOGETHER)
BITE OFF MORE THAN ONE CAN CHEW
BITE ONE'S TONGUE
BITE THE BULLET
BITE THE DUST
BLACK AND WHITE
BLEED RED INK
BLOW A FUSE/GASKET
BLOW HOT AND COLD
BLOW ONE'S TOP
BLOW SMOKE
BLOW STH OUT OF PROPORTION
BLUE BLOOD
BORN WITH A SLIVER SPOON IN ONE'S MOUTH
BREAD-AND-BUTTER
BREAK A LEG!
BREAK THE BANK
BREATHE FIRE
BRING HOME THE BACON
BRING ONE'S A-GAME
BRING STH HOME
BUCK NAKED
BUCK THE SYSTEM
BUILD BRIDGES
BURN A HOLE IN ONE'S POCKET
BURN BOATS/BRIDGES
BURN/BLOW MONEY
BURST A BLOOD VESSEL
BURST OUT CRYING
BURST OUT LAUGHING
BURY ONE'S HEAD IN SAND
BUTTON ONE'S LIP
BY FAIR MEANS OR FOUL
BY HOOK OR BY CROOK
BY HOOK OR CROOK
BY LEAPS AND BOUNDS
BY THE BOOK
BY THE LOOK OF THINGS
BY THE WORD OF MOUTH
BY WORD OF MOUTH
CALL A SPADE A SPADE
CALL IT A DAY
CALL IT QUITS
CALL THE SHOTS
CAN'T HOLD A CANDLE
CARRY THE CAN
CARRY/TAKE STH TO EXTREMES
CAST ASPERSIONS ON SB
CATCH SB IN THE ACT
CATCH SB RED-HANDED
CATCH SB WITH THEIR PANTS DOWN
CHANCE ONE'S ARM
CHANCES ARE
CHASE ONE'S TAIL
CHEAT DEATH
CHICKEN OUT
CHILD'S PLAY
CHILL SB TO THE BONE/MARROW
CHOP AND CHANGE
CHOPPED LIVER
CLEAN UP ONE'S ACT
CLEAR THE AIR
CLEVER CLOGS
CLIMB THE WALLS
CLIMB TO THE TOP OF THE CAREER LADDER
CLOSE ONE'S EARS
COME APART AT THE SEAMS
COME BACK TO ONE'S SENSES
COME CLEAN
COME HELL OR HIGH WATER
COME HOME TO SB
COME IN FOR BLAME
COME RAIN OR SHINE
COME TO NOTHING
COME TO SB'S RESCUE
COME UNDER FIRE
COME UP AGAINST A BRICK WALL
COME WHAT MAY
COMMIT STH TO MEMORY
CONNECT THE DOTS
COOK SB'S GOOSE
COST A PRETTY PENNY
COST A SMALL FORTUNE
COST AN ARM AND A LEG
COST NEXT TO NOTHING
COULDN'T CARE LESS
COUNT PENNIES
CROSS SB'S MIND
CROSS THE T'S AND DOT THE I'S
CRUNCH THE NUMBERS
CRY BUCKETS
CRY FOR THE MOON
CUDGEL ONE'S BRAINS
CUSHION THE BLOW
CUT FROM THE SAME CLOTH
CUT ONE'S LOSSES
DE TROP
DEVIL-MAY-CARE
DICE WITH DEATH
DIFFERENT STROKES FOR DIFFERENT FOLKS
DIG SB'S HEELS IN
DIP ONE'S TOES IN THE WATER
DISSOLVE INTO LAUGHTER
DISSOLVE INTO TEARS
DO SB A POWER OF GOOD
DO SB A WORLD OF GOOD
DO STH FOR KICKS
DO STH ON A WHIM
DO STH WHEN SB'S BACK IS TURNED
DO STH WITH FLYING COLORS
DO STH WITH ONE ARM TIED BEHIND SB'S BACK
DO THE TRICK
DODGE AND WEAVE
DON'T COUNT SB'S CHICKENS BEFORE THEY HATCH
DON'T JUDGE THE BOOK BY ITS COVER
DRAW A BLANK
DRAW THE SHORT STRAW
DRIVE SB CRAZY/NUTS
DRIVE SB TO DISTRACTION
DRIVE SB UP THE WALL
DRIVE/SEND SB ROUND THE BEND
DYED-IN-THE-WOOL
EACH SB'S OWN
EARN ONE'S CRUST
EARN/TURN AN HONEST PENNY
EASE THE TENSION
EASY STREET
EAT SB'S LUNCH
EAT SLEEP AND BREATHE STH
ELEPHANT IN THE ROOM
EVERY TOM DICK AND HARRY
FACE THE MUSIC
FAIL BY THE WAYSIDE
FAINT HEART NEVER WON FAIR LADY
FALL INTO PLACE
FALL OFF ONE'S PERCH
FALL OFF THE BACK OF A LORRY
FALL ON DEAF EARS
FALL ON STONY GROUND
FALL SHORT OF
FEATHER ONE'S OWN NEST
FEED SB A LINE
FEEL AS RIGHT AS RAIN
FEEL AT HOME
FEEL BELOW PAR
FEEL OFF-COLOR
FEEL THE PINCH
FELL/BE ON TOP OF THE WORLD
FIGHT A LOSING BATTLE
FIGHT SHY OF
FIND OUT HOW THE LAND LIES
FIRST-CLASS
FIRST-RATE
FIT AS A FIDDLE
FIT LIKE A GLOVE
FLAY SB ALIVE
FLIP ONE'S LID
FLOAT SB A LOAN
FLOAT SB'S BOAT
FLOG A DEAD HORSE
FLY INTO A RAGE
FLY OFF THE HANDLE
FOLLOW A DIFFERENT COURSE OF ACTION
FOOT THE BILL
FOR GOOD LUCK
FORTUNE FAVOUR THE BOLD/BRAVE
FORTUNE SMILES ON SB
FREE REIN
GARDEN VARIETY
GET A BUZZ OUT OF STH
GET A PIECE OF THE ACTION
GET A REAL KICK OUT OF STH
GET A RUN FOR ONE'S MONEY
GET A SHORT END OF THE STICK
GET AWAY SCOT FREE
GET AWAY WITH MURDER
GET BACK ON ONE'S FEET
GET BEYOND A JOKE
GET COLD FEET
GET HEAVY
GET HOLD OF THE WRONG END OF THE STICK
GET IN AT THE GROUND FLOOR
GET IN ON THE ACT
GET INTO A LATHER
GET ON LIKE A HOUSE ON FIRE
GET ON SB'S NERVES
GET ON SB'S WICK
GET SB'S ACT TOGETHER
GET TEARY-EYED
GET THE HEEBIE-JEEBIES
GET THE JITTERS
GET THE PICTURE OF
GET THE SILENT TREATMENT
GET THE UPPER HAND
GET TO GRIPS WITH
GET TO THE BOTTOM OF
GET UP ON THE WRONG SIDE OF THE BED
GET UP SB'S NOSE
GET WIND OF STH
GIVE AND TAKE
GIVE GROUND
GIVE IT A SHOT/WHIRL
GIVE IT TO SB STRAIGHT
GIVE SB A BACKHANDER
GIVE SB A HARD TIME
GIVE SB A LEG UP
GIVE SB A PIECE OF ONE'S MIND
GIVE SB AN EARFUL
GIVE SB HELL
GIVE SB THE BENEFIT OF THE DOUBT
GIVE SB THE COLD SHOULDER
GIVE STH UP AS A BAD JOB
GIVE UP THE GHOST
GO ABOVE AND BEYOND
GO APE/NUTS/POSTAL
GO BALLISTIC
GO BANANAS
GO DOWN IN FLAMES
GO DOWN THE DRAIN
GO DOWN THE PLUGHOLE
GO DUTCH
GO FROM BAD TO WORSE
GO FROM ONE EXTREME TO ANOTHER
GO FROM STRENGTH TO STRENGTH
GO IN BLIND
GO INTO RAPTURES
GO INTO RHAPSODIES
GO OFF ON A TANGENT
GO OFF ON ONE
GO OFF THE DEEP END
GO OFF THE RAILS
GO ONE BETTER
GO PLACES
GO ROUND IN CIRCLES
GO SHARES
GO SPARE
GO THROUGH THE BACK DOOR
GO THROUGH THE ROOF
GO TO ANY LENGTHS
GO TO GREAT LENGTHS
GO TO GREAT PAINS
GO TO PIECES
GO TOE TO TOE
GO/COME UP IN THE WORLD
GOLD-PLATED
GOLDEN BOY
GOLDEN MEAN
GRASP/CLUTCH AT STRAWS
GREASE ONE'S PALM
GRIN AND BEAR IT
GRIT SB'S TEETH
HALFWAY HOUSE
HANG BY A THREAD
HANG IN THERE
HAVE A BAD TIME
HAVE A BALL
HAVE A BASH AT
HAVE A BEE IN ONE'S BONNET
HAVE A BLAST
HAVE A BONE TO PICK WITH SB
HAVE A CHANGE OF HEART
HAVE A FACE LIKE THE WET WEEKEND
HAVE A FINGER IN EVERY PIE
HAVE A FOOT IN BOTH CAMPS
HAVE A GOOD GOING
HAVE A HEART OF GOLD
HAVE A HEAVY HEART
HAVE A LOT OF IRONS IN THE FIRE
HAVE A LOT ON ONE'S PLATE
HAVE A LOT ON SB'S MIND
HAVE A LOT TO ANSWER FOR
HAVE A LUMP IN ONE'S THROAT
HAVE A PIT IN ONE'S STOMACH
HAVE A SCREW LOOSE
HAVE A SHORT FUSE
HAVE A SOFT SPOT FOR
HAVE A WHALE OF A TIME
HAVE BUTTERFLIES IN SB'S STOMACH
HAVE DEEP POCKETS
HAVE IT IN FOR SB
HAVE IT UP TO HERE
HAVE LONG/ GOOD INNINGS
HAVE MONEY TO BURN
HAVE MORE MONEY THAN SENSE
HAVE NERVES OF STEEL
HAVE NOTHING TO SAY FOR ONESELF
HAVE ONE'S FEET ON THE GROUND
HAVE ONE'S FOOT IN THE GRAVE
HAVE ONE'S HANDS FULL
HAVE ONE'S HEAD SCREWED ON
HAVE ONE'S HEART IN THE RIGHT PLACE
HAVE ONE'S PANTIES IN A BUNCH
HAVE ONE'S STOMACH IN KNOTS
HAVE SB BY THE BALLS
HAVE SB EATING OUT OF ONE'S HAND
HAVE SB'S EYES ON THE BALL/PRIZE
HAVE SB'S GUTS FOR GARTERS
HAVE SB'S NAME IN THE LIGHTS
HAVE SB'S SAY
HAVE SB/STH IN THE PALM OF ONE'S HAND
HAVE STH ON THE BRAIN
HAVE THE BALLS TO DO STH
HAVE THE BLUES
HAVE THE BRASS
HAVE THE MEASURE OF STH
HAVE THE NERVE TO DO STH
HAVE THE PATIENCE OF A SAINT
HAVE THE TIME OF ONE'S LIFE
HAVE/GET ONE'S FINGERS BURNED
HAVE/THROW A FIT
HEADS WILL ROLL!
HEAR STH FIRST HAND
HEAR STH THORUGH A GRAPEVINE
HELL-BENT ON STH
HIGH-PROFILE
HIT IT BIG TIME
HIT THE BALL OUT OF THE PARK
HIT THE CEILING/ROOF
HIT THE GROUND RUNNING
HIT THE JACKPOT
HIT THE NAIL ON THE HEAD
HIT THE SACK
HIT-OR-MISS
HOLD SB'S GROUND
HOLD THE REINS
HOLD THE WHIP HAND
HOLD/BEAR A GRUDGE AGAINST
HOLD/STAND FAST
HONESTY IS THE BEST POLICY
HOPE FOR PATHS TO CROSS
HORSE AROUND
I WASN'T BROUGHT UP IN THE WOODS TO BE SCARED BY OWLS
IF IT AIN'T BROKE DON'T FIX IT
IN A BLINK OF AN EYE
IN BLACK AND WHITE
IN FOR A PENNY IN FOR A POUND
IN HOT WATER
IN ONE'S BIRTHDAY SUIT
IN PIG'S EYE
IN PLAIN SIGHT
IN SHORT/MEDIUM/LONG TERM
IN SMALL DOSES
IN THE BACK OF BEYOND
IN THE BAG
IN THE BUFF
IN THE LAP OF LUXURY
IN THE MIDDLE OF NOWHERE
IN THE RAW
IN THE STICKS
IN THE WORKS
IT REMAINS TO BE SEEN
IT'S THE THOUGHT THAT COUNTS
JALL WORK AND NO PLAY MAKES JACK A DULL BOY
JOHN Q. PUBLIC
JUMP DOWN SB'S THROAT
JUMP FOR JOY
JUMP ON THE BANDWAGON
JUMP OUT OF SB'S SKIN
JUMP THROUGH HOOPS
JUMP TO CONCLUSIONS
KEEP A COOL HEAD
KEEP A LOW PROFILE
KEEP BODY AND SOUL TOGETHER
KEEP IN MIND
KEEP IN TOUCH WITH SB
KEEP IT REAL
KEEP ONE'S COOL
KEEP ONE'S FINGERS CROSSED
KEEP ONE'S HAIR ON
KEEP ONE'S HEAD
KEEP ONE'S HEAD ABOVE WATER
KEEP ONE'S MOUTH SHUT
KEEP ONE'S WITS ABOUT ONE
KEEP ONESELF TO ONESELF
KEEP SB AT ARM'S LENGTH
KEEP SB ON A TIGHT REIN
KEEP STH AT BAY
KEEP THE WOLF FROM THE DOOR
KEEP/PUT ONE'S NOSE TO THE GRINDSTONE
KICK THE BUCKET
KNOCK STH/SB OUT OF THE PARK
KNOW STH LIKE THE BACK OF SB'S HAND
KNOW STH OFF THE CUFF
LABOUR OF LOVE
LARGER THAN LIFE
LAY DOWN THE LAW
LAY ONE'S CARDS ON THE TABLE
LAY STH AT SB'S DOOR
LAY STH ON THE LINE
LEAD SB ASTRAY
LEAN OVER BACKWARDS
LEAVE A BAD TASTE IN ONE'S MOUTH
LEAVE A LOT TO BE DESIRED
LEAVE WITHOUT A BACKWARD GLANCE
LET ONE'S HAIR DOWN
LET SLEEPING DOGS LIE
LIE DOWN ON THE JOB
LIE LIKE A RUG
LIE THROUGH ONE'S TEETH
LIFT SB'S SPIRIT
LIGHTEN THE TONE
LIKE A BEAR WITH A SORE HEAD
LIKE A CAT ON A HOT TIN ROOF
LIKE A SQUARE PEG IN A ROUND HOLE
LIKE GREASED LIGHTNING
LIKE WATCHING PAINT DRY
LINE ONE'S POCKETS
LIVE A LIE
LIVE AND BREATHE STH
LIVE FROM HAND TO MOUTH
LIVE HIGH ON THE HOG
LIVE IN A CLOVER
LIVE LIKE A KING/LORD
LIVE OFF THE FAT OF THE LAND
LIVE ON THE BREADLINE
LIVE TO A RIPE OLD AGE
LIVE UP TO ONE'S EXPECTATIONS
LOOK AFTER THE PENNIES AND THE POUNDS WILL LOOK AFTER YOU
LOOK DAGGERS AT SB
LOOK LIKE DEATH WARMED UP
LOOK TO ONE'S LAURELS
LOSE HEART
LOSE IT
LOSE ONE'S COOL
LOSE ONE'S HEAD
LOSE ONE'S MARBLES
LOSE ONE'S RAG
LOSE ONE'S TEMPER
LOSE ONE'S WAY
LOSE THE PLOT
LOUD MOUTH
MAKE A FRESH START
MAKE A GO OF
MAKE A KILLING
MAKE A MOUNTAIN OUT OF A MOLEHILL
MAKE A NAME FOR ONESELF
MAKE A PIG'S EAR OUT OF
MAKE A SPLASH
MAKE ALL THE DIFFERENCE
MAKE AN ELEPHANT OUT OF A FLY
MAKE AN HONEST LIVING
MAKE ENDS MEET
MAKE FUN OF
MAKE IT BIG
MAKE MATTERS WORSE
MAKE NO BONES ABOUT
MAKE ONE'S BLOOD BOIL
MAKE ONE'S HAIR STAND ON END
MAKE PLAIN
MAKE SB'S BLOOD RUN COLD
MAKE SB'S DAY
MAKE SB'S HACKLES RISE
MAKE SB'S SKIN CRAWL
MAKE UP ONE'S MIND
MAKE YOURSELF AT HOME
MANY HANDS MAKE LIGHT WORK
MEAN BUSINESS
MEND ONE'S WAYS
MIDDLE GROUND
MIDDLE-OF-THE-ROAD
MIDDLE-OFF-THE-ROAD
MISS THE POINT
MOANING MINNIE
MONEY DOESN'T GROW ON TREES
MONEY FOR JAM
MONEY FOR OLD ROPE
MONEY TALKS
MOVE WITH THE TIMES
MOVER AND SHAKER
MUCH OF A MUCHNESS
MURPHY'S LAW
NICKEL-AND-DIME
NINE TIMES OUT OF TEN
NITTY-GRITTY
NO GREAT SHAKES
NO HOLDS BARRED
NO PRIZES FOR GUESSING
NO-NAME
NOSE IN THE AIR
NOT BE A PATCH ON
NOT BE SHORT A BOB OR TWO
NOT FOR ALL THE TEA IN CHINA
NOT FOR LOVE NOR MONEY
NOT IN ONE'S RIGHT MIND
NOT THE SHARPEST KNIFE IN THE DRAWER
NOT TO BE A BARREL OF LAUGHS
NOT TO BE ALL IT'S CRACKED UP TO BE
NOT TO BE IN THE SAME LEAGUE
NOT TO BE WORTH BEANS
NOT TO BUDGE AN INCH
NOT TO GET A WORD IN EDGEWAYS
NOT TO HAVE A DIME TO ONE'S NAME
NOT TO HAVE A MINUTE TO CALL ONE'S OWN
NOT TO HAVE A PENNY TO ONE'S NAME
NOT TO HAVE A SNOWBALL'S CHANCE IN HELL
NOT TO MINCE WORDS
NOT TO PULL ANY PUNCHES
NOT TO SEE THE FOREST/WOOD FOR THE TREES
NOT TO TAKE NO FOR AN ANSWER
NOT WORTH A DIME
NOTHING OUT OF ORDINARY
NOTHING TO WRITE HOME ABOUT
NOTHING VENTURED NOTHING GAINED
OF DIFFERENT BREED
OFF BASE
OFF BEAM
OFF THE BEATEN TRACK
OFF THE HOOK
OFF THE TOP OF ONE'S HEAD
OFF-THE-CUFF
OIL THE WHEELS
ON A REAL NOTE
ON ONE'S WAY UP
ON TENTERHOOKS
ON THE FACE OF IT
ON THE MARK
ON THE RIGHT SIDE OF THE LAW
ON THE RIGHT TRACK
ON THE SAME PAGE
ON THE SHOESTRING
ON THE SPUR OF THE MOMENT
ON THE THRESHOLD OF
ON THE WRONG SIDE OF THE LAW
ON THE WRONG TRACK
ONCE IN A BLUE MOON
ONE CAN TAKE IT TO THE BANK
ONE COULD HAVE HEARD A PIN DROP
ONE WAY OR ANOTHER
ONE'S DAILY BREAD
ONE'S HEART IS NOT IN IT
ONE'S HEART SKIPS/MISSES A BEAT
OPEN ONE'S HEART TO SB
OPEN THE DOOR FOR
OPEN THE FLOODGATES
OPEN THE WAY FOR
OUT OF POCKET
OUT OF SIGHT OUT OF MIND
OUT OF THE ARK
OVER MY DEAD BODY
OVER ONE'S DEAD BODY
OVERSTEP THE MARK
PAINT THE TOWN RED
PASS THE BUCK
PAY LIP SERVICE
PAY OVER THE ODDS
PAY THE PENALTY
PAY THE PRICE FOR
PAY THROUGH THE NOSE
PENNY-ANTE
PEOPLE WHO LIVE IN GLASS HOUSES SHOULDN'T THROW STONES
PICK UP THE BILL
PICK UP THE PIECES
PICK UP THE TAB
PICK UP THE THREADS
PICTURE-PERFECT
PIE IN THE SKY
PIECE DE RESISTANCE
PIERCE SB'S HEART
PIGS MIGHT FLY
PILE ON THE AGONY
PINCH THE PENNIES
PIQUE SB'S CURIOSITY/INTEREST
PITCH IN TO HELP
PLAY DEVIL'S ADVOCATE
PLAY DIRTY POOL
PLAY GAMES
PLAY IT SAFE
PLAY SECOND FIDDLE
PLAY SILLY BAGGERS
PLAY THE FIRST FIDDLE
PLAY WITH FIRE
PLUCK A NUMBER OUT OF THIN AIR
PLUCK UP ONE'S COURAGE
POINT THE FINGER AT SB
POKE FUN AT
POKER FACE
POP ONE'S CLOGS
POUR SB'S HEART OUT
PRACTICE MAKES PERFECT
PRE-EMINENT
PREY ON ONE'S MIND
PULL IN ONE'S HORNS
PULL NO PUNCHES
PULL SB'S CHAIN
PULL SB'S LEG
PULL SB'S SOCKS UP
PULL THE STRINGS
PULL THE WOOL OVER ONE'S EYES
PULL WOOL OVER SB'S EYES
PUSH THE BOAT OUT
PUSH THE PANIC BUTTON
PUT A CRIMP IN
PUT A DAMPER ON
PUT ALL SB'S EGGS INTO ONE BASKET
PUT ON A FA ADE
PUT ON AN ACT
PUT ONE'S MONEY WHERE ONE'S MOUTH IS
PUT SB'S BACK UP
PUT SB'S FOOT IN IT
PUT SB'S HEART AND SOUL INTO STH
PUT STH UNDER THE MICROSCOPE
PUT THE BRAKES ON
PUT THE CAT AMONG THE PIDGEONS
PUT TWO AND TWO TOGETHER
PUT/GET SB'S BACK UP
PUT/LEAVE SB IN THE SHADE
QUEER SB'S PITCH
RACK ONE'S BRAIN
RAGS-TO-RICHES
RAIN ON SB'S PARADE
RAISE HELL
RATTLE SB'S CAGE
REACH FEVER PITCH
RECHARGE ONE'S BATTERIES
REST ON ONE'S LAURELS
RIDE OUT THE STORM
RISE TO FAME
RISE TO THE OCCASION
RISK IT FOR A BISCUIT
RISK LIFE AND LIMB
ROB PETER TO PAY PAUL
ROME WASN'T BUILT IN A DAY
RUB SB THE WRONG WAY
RUFFLE SB'S FEATHERS
RULE THE ROOST
RUN AROUND IN CIRCLES
RUN AROUND LIKE A HEADLESS CHICKEN
RUN SB CLOSE
RUN THE RISK OF
RUN-OF-THE-MILL
RUN/GO/WORK LIKE A DREAM
RUN/WORK LIKE CLOCKWORK
SAIL CLOSE TO THE WIND
SAVE ONE'S BREATH
SB'S MIND GOES BLANK
SCARE SB OUT OF ONE'S WITS
SCARE SB SHITLESS
SCARE THE DAYLIGHT OUT OF SB
SCRAPE A LIVING
SCRATCH BENEATH THE SURFACE
SCRATCH SB'S HEAD
SCRATCH/SCRAPE THE SURFACE
SCREW UP ONE'S COURAGE
SEE EYE TO EYE
SEE HOW THE LAND LIES
SEE HOW THE WIND IS BLOWING
SEE RED
SELL LIKE HOT CAKES
SEND CHILLS DOWN SB'S SPINE
SEND SHIVERS UP/DOWN SB'S SPINE
SET SB'S PULSE RACING
SET SB'S TEETH ON EDGE
SET THE BALL ROLLING
SET THE BAR HIGH
SET THE BAR LOW
SET THE RECORD STRAIGHT
SET THE WHEELS IN MOTION
SHADES OF GREY
SHED A TEAR
SHED LIGHT ON
SHIFT SB'S GROUND
SHOOT A LINE
SHOOT FROM THE HIP
SHOOT STRAIGHT
SHUT ONE'S EYES
SILENCE IS GOLDEN
SITTING PRETTY
SKATE ON THIN ICE
SKIN SB ALIVE
SKY IS THE LIMIT
SLIP SB'S MIND
SLIP THROUGH THE NET
SMALL FRY
SNAP AT SB'S HEELS
SNAP/BITE ONE'S HEAD OFF
SOD'S LAW
SPARK SB'S INTEREST
SPEAK ONE'S MIND
SPEND MONEY LIKE WATER
SPLIT STH RIGHT DOWN THE MIDDLE
SPOT ON
SPREAD ONESELF TOO THIN
SPREAD THE WORD
SQUARE THE BOOKS/ACCOUNTS
STAB SB IN THE BACK
STAND ONE'S GROUND
STAND OUT FROM THE CROWD
STAND/HOLD FAST
STAND/STICK OUT A MILE
STARE SB IN THE FACE
START FROM SCRATCH
STEADY SB'S NERVES
STEP ON SB'S TOES
STICK IN ONE'S THROAT
STICK ONE'S NECK OUT
STICK OUT LIKE A SORE THUMB
STICK TO ONE'S GUNS
STIR SB'S BLOOD
STRAIGHT FROM THE HORSE'S MOUTH
STRIKE A CHORD
STRIKE GOLD
STRIKE IT LUCKY
STRIKE/TOUCH/HIT A NERVE
STUCK IN A RUT
SUGAR THE PILL
SURROUNDED BY THE GREEN BELT
SWEETEN THE PILL
SWING INTO ACTION
TAKE A SHINE
TAKE A SHOT AT
TAKE A STROLL DOWN THE MEMORY LANE
TAKE A TURN FOR THE BETTER
TAKE A TURN FOR THE WORSE
TAKE ACCOUNT OF
TAKE ONE THING AT A TIME
TAKE ONE'S TIME TO DO STH
TAKE SB'S BREATH AWAY
TAKE STH AT FACE VALUE
TAKE STH BY THE THROAT
TAKE STOCK OF
TAKE THE BLAME
TAKE THE FALL FOR SB
TAKE THE LAW INTO ONE'S OWN HANDS
TAKE THE LUMPS
TAKE THE MICKEY OUT OF
TAKE THE MICKEY OUT OF SB
TAKE THE STING OUT OF
TALK NINETEEN TO THE DOZEN
TALK ONE'S ASS OFF
TALK ONE'S HEAD OFF
TALK SHOP
TALK THE HIND LEGS OFF A DONKEY
TALK TURKEY
TEAR/RIP STH/SB TO SHREDS
TELL IT LIKE IT IS
TEMPERS GET FRAYED
THE ANSWER TO MY PRAYERS
THE BONES
THE BOTTOM OF THE HEAP
THE BULL'S EYE
THE CHERRY ON TOP
THE EARLY BIRD CATCHES THE WORM
THE FINAL/LAST STRAW
THE FINE PRINT
THE FLOWER OF
THE GRASS IS ALWAYS GREENER ON THE OTHER SIDE
THE GREAT UNWASHED
THE HEART OF THE MATTER
THE HOI POLLOI
THE INS AND OUTS OF STH
THE JEWEL IN THE CROWN
THE LIFE AND SOUL OF THE PARTY
THE MOON ON A STICK
THE NAME OF THE GAME
THE NUTS AND BOLTS
THE PROOF OF THE PUDDING IS IN THE EATING
THE SCUM OF THE EARTH
THE SHAPE OF THINGS TO COME
THE SMALL PRINT
THE THIRD ESTATE
THE TIP OF THE ICEBERG
THE UPPER CRUST
THE WORLD IS SB'S OYSTER
THERE IS METHOD IN ONE'S MADNESS
THERE IS NO ACCOUNTING FOR TASTE
THINK ON ONE'S FEET
THINK THE WHOLE WORLD REVOLVES AROUND ONE
THROUGH AND THROUGH
THROW A SPANNER IN THE WORKS
THROW A TANTRUM
THROW A WOBBLY
THROW CAUTION TO THE WIND
THROW DUST IN SB'S EYES
THROW DUST INTO ONE'S EYES
THROW IN THE TOWEL
THROW MONEY AROUND
THROW ONE'S MONEY DOWN THE DRAIN
THROW ONE'S TOYS OUT OF THE PRAM
THROW ONE'S WEIGHT AROUND
THROW SOMEONE FOR A LOOP
THROW THE BOOK AT SB
TIE ONESELF UP IN KNOTS
TIE UP A FEW LOOSE ENDS
TIGHTEN ONE'S BELT
TONGUE IN CHEEK
TOO MANY COOKS SPOIL THE BROTH
TOUCH/KNOCK ON WOOD
TOUR DE FORCE
TRIAL AND ERROR
TRY ONE'S HAND
TURN A BLIND EYE
TURN A DEAF EAR
TURN ON THE WATERWORKS
TURN ONE'S STOMACH
TURN OVER A NEW LEAF
UNDER THE TABLE
UNDER THE WEATHER
UP THE CREEK
UP-AND-COMING
UPPER ECHELON
UPSET THE APPLE CART
VENT ONE'S SPLEEN
VICIOUS CYCLE/CIRCLE
VOICE ONE'S CONCERN
VOLTE-FACE
VOTE WITH ONE'S DOLLARS
VOTE WITH ONE'S WALLET
WATCH THIS SPACE
WAVE A MAGIC WAND
WEAR SB'S HEART ON SB'S SLEEVE
WEATHER THE STORM
WELL-TO-DO
WET BLANKET
WHAT THE FUTURE HOLDS
WHAT'S DONE IS DONE
WHAT'S THE BETTING?
WHEN ALL IS SAID AND DONE
WHEN HELL FREEZES OVER
WHEN THE GOING GETS TOUGH, THE TOUGH GETS GOING
WHILE THE CAT'S AWAY THE MICE WILL PLAY
WHISTLE IN THE DARK
WIDE OFF THE MARK
WILLY NILLY
WIN BIG
WITH BATED BREATH
WITHOUT A SHADOW OF A DOUBT
WORDS FAIL ME
WORK AGAINST THE CLOCK
WORK AT CROSS-PURPOSES
WORK LIKE A CHARM
WORK LIKE MAGIC
WORK ONE'S FINGERS OT THE BONE
WORK SB'S BUTT/ASS OFF
WORK/DO WONDERS
YOU SCRATCH MY BACK AND I'LL SCRATCH YOURS
YOU SNOOZE, YOU LOSE
ZIP ONE'S LIP
LEAVE SB TO ONE'S OWN DEVICES
GET SB'S FINGER OUT
: HIT THE CEILING/ROOF
CREAM OF THE CROP
A DODDLE
PLUCK UP THE COURAGE
BE FED UP TO THE BACK TEETH WITH
TO PULL SB'S WEIGHT
SILVER LINING
A SLAP ON THE WRIST
NOT WORTH BEANS
A TOUGH NUT TO CRACK
HEAR STH THROUGH A GRAPEVINE
HAVE A BONE TO PICK
WORRYWART
DUMB AS A BOX OF A DIPSTICK
THROW A TANTRUM/FIT
JOG SB'S MEMORY
AT SEA
TO GET HOLD OF THE WRONG TREE
SLOW ON THE UPTAKE
SLOG AWAY
TO KNOW ZIP ABOUT
ONCE IN A LIFETIME
OUT OF BLINK
KEEP SB ON A SHORT LEASH
GO IN ONE AR AND OUT THE OTHER
TO BE ALL GREEK
TO GET THE PICTURE/MESSAGE
BE BAD LUCK ON
TO BE SITTING ON THE FENCE
TO BE OVER SB'S HEADS
GET THE DRIFT OF
AT THE BREAK OF DAWN
SPRING TO SB'S MIND
NOT TO KNOW BEANS ABOUT
TO GET CHOKED UP
IN A TIGHT CORNER
IN NO TIME AT ALL
A KNIGHT ON A WHITE HORSE
BE IN THE SPOTLIGHT
CR?ME DE LE CR?ME
NOT A DIME TO ONE'S NAME
COMMON GROUND
SPREAD YOURSELF TOO THIN
RIGHT UP SB'S ALLEY/STREET
TO MESS WITH SOMEONE'S HEAD
BE A JACK OF ALL TRADES (A MASTER OF NONE)
BETAKE ACCOUNT OF
LOOK DAGGERS
A PAIN IN THE NECK/ARSE
COUCH POTATO
TO BE ONLY A MATTER OF TIME
EASE AS PISSING
BALANCING ACT
A STATE OF NERVES
CREATURE COMFORTS
TO COME TO TERMS WITH
RUN RINGS AROUND
TURN SB'S STOMACH
BACK IN THE GAME
COOL
SHOOT THE BREEZE
FOR A SONG
SLEEP AND BREATHE STH
NOT MINCE WORDS
PUT ON A GOOD SHOW
NOT BE ALL HERE
CUT CORNERS
BE TOFFEE NOSED
LIKE WATER OFF DUCK'S BACK
OUT OF ONE'S DEPTH
TO LOSE TRUST
WITH FLYING COLOURS
FIGHT TOOTH AND NAIL
STICK TO SB'S GUNS
LIKE WATER AND OIL
PET PEEVE
NOT BE CLEAR TO SB
BE OUT OF ELEMENT
HAVE ONE'S EYES ON THE BALL/PRIZE
EASY AS PIE
FINDING A NEEDLE IN A HAYSTACK
ON THE FACE
THE TOUGH GETS GOING
TO TAKE THE WORLD BY STORM
IN A TIGHT SPOT
TO PUT FINISHING TOUCHES ON
NOT ALL IT'S CRACKED UP TO BE
RUN IN CIRCLES
AT SB'S WITS END
SEARCH ME
LEARN STH BY ROTE
THE BOTTOM HEAP
SB'S AVERAGE BEAR
PLAY SAFE
GET ON LIKE A HOUSE OF FIRE
ETCHED IN SB'S MEMORY
EASY AS A PIE
LONE WOLF
TO BE AT SB'S WITS END
IN THE JOYS OF SPRING
IN SB'S MIND'S EYE
TOP-DRAWER
A QUANTUM LEAP
AT A SNAIL'S PACE
IN THE AIR
CHANCE SB'S ARM
GET ONE'S WIRES CROSSED
TO MOVE MOUNTAINS
ON AND OFF
GET THE SHORT END OF THE STICK
AT SB'S WIT END
STATE-OF-THE-ART
AT A MOMENT'S NOTICE
GO DOWNHILL
KEEP THE WOLF AT THE DOOR
HEDGE ONE'S BETS
AS SOUND AS BELL
AS PLAIN AS THE NOSE ON SB'S FACE
A ROUGH RIDE
BE A FOREGONE CONCLUSION
PULL SB'S WEIGHT
AS SURE AS DAY
TO BURN THE MIDNIGHT OIL
BE AS FUNNY AS A BARREL OF MONKEYS
A GUTLESS WONDER
BE IN FULL SWING
ICING OF THE CAKE
BE HELL-BENT
BURN THE MIDNIGHT OIL
SPLIT RIGHT DOWN THE MIDDLE
GOOF AROUND
TO HIT A SNAG
MAKER AND SHAKER
GROUND-BREAKING
BE A MOVER AND SHAKER
ETCHED INTO SB'S MEMORY
TO PLUCK UP THE COURAGE
FOOL'S PARADISE
OUT-DATED
A TIGHT SPOT
TO BLOW A FUSE
AT THE END OF THE DAY
PUBLIC
OUT OF ELEMENT
BE ALL TALK AND NO ACTIONS
LIKE FINDING A NEEDLE IN A HAYSTACK
LIKE APPLES AND ORANGES
HAVE LONG/GOOD INNINGS
BORN WITH A SILVER SPOON IN ONE'S MOUTH
BE IN THE JOYS OF SPRING
BE LIKE WATER OFF A DUCK'S BACK
KNOW SB'S ONIONS
BE ALIVE AND WELL
BUTON ONE'S LIP
LEARN THE TRUTH
TO SPREAD YOURSELF TOO THIN
NOLENS VOLENS
BOG-STANDARD
LIKE GETTING BLOOD OUT OF A STONE
OUT OF LINE
PROS AND CONS
PAY THE PENALTY FOR
TOUGH LUCK
TO PUT FINISHING TOUCHES
TO WRAP ONE'S HEAD AROUND
A DOODLE
BE UP TO ONE/S EYES/EARS IN
DOWN IN THE DUMPS
BE DOG-TIRED
A NIGH IMPOSSIBLE
TALL ORDER
SILENT AS THE DEAD
BE THE APPLE OF ONE'S EYE
FEEL/BE ON TOP OF THE WORLD
DO STH WITH FLYING COLOURS
TO AS RARE AS HEN'S TEETH
TO RUN RINGS AROUND
MAGNUM OPUS
A JACK OF ALL TRADES
TO GET THE DRIFT OF
TO KNOW ZIP ABOUT STH
HIT THE HAY
BE RIGHT UP SB'S ALLEY/STREET
PLAIN SAILING
SILENT AS THE GRAVE
BE IN THE DARK IDIOMS
GO/COME DOWN IN THE WORLD
LAYPERSON
AS EASY AS PIE
WHAT'S THE BETTING
THE MORE THE MERRIER
NOT CUT IT
COOL CALM AND COLLECTED
GO THROUGH THE MOTIONS
THROW DUST INTO SB'S EYES
IN THE BLACK MONEY SPINNER
WRAP ONE'S HEAD AROUND
PET HATE
TO HAVE A BRAINWAVE
ALL OVER THE PLACE
AT THE EDGE OF SB'S SEAT
BE ON THE WARS
DOWN-TO-EARTH
OVER THE TOP
CHILL SB TO THE BONE MARROW
BE AFRAID OF ONE'S OWN SHADOW
HAVE AN ABOUT-FACE
GO BLIND
CHATTERBOX
TO BE LIKE APPLES AND ORANGES
LIKE BANGING ONE'S HEAD AGAINST A BRICK WALL
TO KNOW STH INSIDE OUT
IN ONE EAR OUT THE OTHER
IN A HEARTBEAT
BE SOUR GRAPES
NOT KNOW BEANS ABOUT
BE A NASTY PIECE OF WORK
GRASP THE NETTLE
LEARN STH BY HEART/ROTE
PRIME EXAMPLE OF
A COUCH POTATO
BE A JACK OF ALL TRADES
NOT TO HAVE A SNOWBALL'S CHANCE OF HELL
BE DANCING IN THE STREETS
BEAR/HOLD A GRUDGE
NOT TO SLEEP A WINK
RATEPAYER
TO GO BACK TO THE DRAWING BOARD
FULL OF THE MILK OF HUMAN KINDNESS
TAXPAYER
HAPPY-GO-LUCKY
IF MY MEMORY SERVES ME RIGHT
TO FEEL THE BLUES
ONCE IN BLUE MOON
AS STRAIGHT AS AN ARROW
SHOW ONE'S TRUE COLOURS
LEARN STH BY HEART
GET AWAY SCOT-FREE
BLOOD SWEAT AND TEARS
GO OVERBOARD
IN A STATE OF NERVES
KNOW SB'S STUFF
TO GET A MOVE ON
HAVE SB'S BACK AGAINST THE WALL
GARDEN-VARIETY
TO MAKE CRYSTAL CLEAR
IN THE FINE PRINT
ETCH STH IN SB'S MEMORY
TO BE ON THE RUN
DIG ONE'S HEELS IN
FEEL OFF-COLOUR
FIND OUT THE TRUTH
PUT THE CAT AMONG THE PIGEONS
TO BE ON THE NOSE
WHEN THE GOING GETS TOUGH
WORK ONE'S FINGERS TO THE BONE
THE ROAD TO HELL IS PAVED WITH GOOD INTENTIONS
KNOW STH INSIDE OUT
CREATURE COMFORT
A SILVER LINING
SLOG ONE'S GUTS OUT
TO BE AT THE EDGE OF SB'S SEAT
IN THE SPOTLIGHT
COME TO LIGHT
TEN TO THE PENNY
CASH COW
TO WIPE THE SLATE CLEAN
SIT ON THE FENCE
DONKEY'S YEARS
CR?ME DE LA CR?ME
THE NEXT BEST THING
SET THE WORLD ON FIRE
MONEY SPINNER
TO SET THE WORLD ON FIRE
ON THE NOSE
TO BE A WORRYWART
NOT BE WORTH BEANS
RUN CIRCLES ROUND
BE AS STUBBORN AS A MULE
TO FALL AT THE SEAMS
A BAD WORKMAN BLAMES SB'S TOOLS
OUT OF THE FRYING PAN INTO THE FIRE
COAST AN ARM AND A LEG
BE A HIGH FLYER
TO BE NIGH IMPOSSIBLE
IN A FLASH
TO BURN THE CANDLE AT BOTH ENDS
PULL WOLL OVER ONE'S EYES
DRIVE SB BANANAS
A DEAD-END
TO ADD FIRE TO THE FIRE
GET OFF TO A FLYING START
NIGH IMPOSSIBLE
TO BE ROLLING IN IT
A KNOWN QUANTITY
TO BE SHITTING BRICKS
BE HIGH AS A KITE
LEAVE SB TO THEIR OWN DEVICES
BE ALL TALK AND NO ACTION
NOT WORTH A BEAN
LEAD SB ON A GOOSE CHASE
ON TOP OF THE WORLD
OUT OF DATE
CHEW THE FAT
GET THE BUZZ OUT OF
COLLECTED
IN THE VANGUARD
MOVE MOUNTAINS
TO GET SB'S FINGER OUT
IN THE DOLDRUMS
OPEN THE DOOR TO
A TALL ORDER
GET THE MESSAGE/ PICTURE
TO DRAG SB'S HEELS
CALM
BE AS PLAIN AS THE NOSE ON ONE'S NOSE
ON A SHOESTRING
TALK AT CROSS PURPOSES
BE LAUGHING ON ONE'S WAY TO THE BANK
TO DIG YOURSELF INTO A HOLE
MAKE ONE'S BLOOD RUN COLD
BE SICK AND TIRED
TO WORK ONE'S FINGERS TO THE BONE
TO SIT ON A FENCE
GIVEN FREE REIN TO
A PET HATE
PAR EXCELLENCE
NOR FOR LOVE NOR MONEY
A DOUBLE-EDGED SWORD
TO GRASP THE NETTLE
JOG ONE'S MEMORY
GO IN ONE EAR AND OUT THE OTHER
TO LEARN STH BY HEART
STUCK IN ONE'S OLD WAYS
BREADWINNER
AN APOLOGY FOR STH
BE NIGH IMPOSSIBLE
A FOREGONE CONCLUSION
EAT
WITHOUT A SECOND THOUGHT
STATE OF THE ART
HAVE HAD ONE'S FILL
BE AT TOP OF ONE'S GAME
NOT SHORT A BOB OR TWO`.split("\n");