"use strict";

const list_of_idioms = `A BACKSEAT DRIVER
A BALANCING/JUGGLING ACT
A BALL OF FIRE
A BLESSING IN DISGUISE
A BLOT ON SB'S CHARACTER
A BRAINBOX
A BREEZE
A BRIGHT SPARK
A BROWN STUDY
A BRUSH WITH FAME
A BUGBEAR
A CASTLE IN THE AIR
A CHINK IN THE ARMOUR
A CLEVER DICK
A COLD FISH
A DEAD END
A DEAD HAND OF
A DIME A DOZEN
A DOWNWARD SPIRAL
A FAR CRY FROM
A FAUX PASS
A FEATHER IN ONE'S CAP
A FISH OUT OF WATER
A FLASH IN THE PAN
A FLY IN THE OINTMENT
A FOOL'S ERRAND
A FUDDY DUDDY
A GO-GETTER
A HAPPY CAMPER
A HELPING HAND
A HIVE ACTIVITY
A HOUSEHOLD NAME
A HUSTLE AND BUSTLE
A KNOW-IT-ALL
A LIFELINE
A LIGHT AT THE END OF THE TUNNEL
A LIVE WIRE
A LONG FACE
A MAGIC TOUCH
A MISERY GUTS
A MIXED BLESSING
A NIGHT OWL
A PAIN IN THE ARSE/BACKSIDE
A PAIN IN THE NECK
A PARTY ANIMAL
A PARTY POOPER
A PENCHANT FOR
A PENNY FOR SB'S THOUGHTS
A PEOPLE PERSON
A PIECE OF CAKE
A PIPE DREAM
A ROARING SUCCESS
A SHOT IN THE ARM
A SLEDGE HAMMER TO CRACK A NUT
A SMART ALEC
A SMART APPLE
A SMART COOKIE
A SMARTY PANTS
A STICK-IN-THE-MUD
A STUMBLING BLOCK
A VICTORY FOR COMMON SENSE
A WALK IN THE PARK
A WEAK SPOT
A WHITE KNIGHT
A WHIZZ-KID
A WISE GUY
A WORLD OF DIFFERENCE
ABOUT-FACE
ABOUT-TURN
ABSENCE MAKES THE HEART GROW FONDER
ACHILLES HEEL
ACT SB'S AGE
ACT/PLAY THE FOOL
ACTIONS SPEAK LOUDER THAN WORDS
ADD FUEL TO FIRE
ADD INSULT TO INJURY
AIRY-FAIRY
ALIVE AND WELL/KICKING
ALL TALK NO ACTION
ALL THE BELLS AND WHISTLES
AN ACE UP ONE'S SLEEVE
AN ARMACHAIR CRITIC
AN AWKWARD CUSTOMER
AN EAGER BEAVER
AN EARLY BIRD
AN UNKNOWN QUANTITY
AN UPHILL BATTLE/STRUGGLE/FIGHT
ANYBODY WHO IS ANYBODY
AS CALM AS A TOAD IN THE SUN
AS COLD AS STONE
AS DULL AS A DITCHWATER
AS FREE AS A BIRD
AS KEEN AS MUSTARD
AS RIGHT AS RAIN
AS SLOW AS THE MOLASSES
AS SLY AS A FOX
AS SMART AS A WHIP
AT A CROSSROADS
AT ODDS
AT THE CRACK OF DAWN
AVANT-GARDE
AVERAGE JOE BLOGGS
AVOID STH LIKE THE PLAGUE
BARE ONE'S SOUL
BARK UP THE WRONG TREE
BAT A THOUSAND
BE (CAUGHT) BETWEEN A ROCK AND A HARD PLACE
BE (RIGHT) ON THE MONEY
BE A (NASTY) PIECE OF WORK
BE A BAD EGG
BE A DARK HORSE
BE A DIPSTICK
BE A GOOD EGG
BE A GOODY-GOODY
BE A HARD ACT TO FOLLOW
BE A HARD/TOUGH NUT
BE A JACK OF ALL TRADES (MASTER OF NONE)
BE A LAMEBRAIN
BE A LONE WOLF
BE A MAN/WOMAN OF HIS/HER WORD
BE A NE'ER-DO-WELL
BE A PILLAR OF SOCIETY
BE A SCAPEGOAT
BE A SHINING EXAMPLE
BE A SHRINKING VIOLET
BE A SLIMEBALL
BE A SNOWFLAKE
BE A SOCIAL BUTTERFLY
BE A STRAIGHT ARROW
BE A WOLF IN SHEEP'S CLOTHING
BE AHEAD OF THE TIMES
BE ALL GREEK TO SB
BE ALL MOUTH AND NO TROUSERS
BE ALL WET
BE AN APOLOGY FOR
BE AN OPEN BOOK
BE AS BRIGHT AS A BUTTON
BE AS DAFT AS A BRUSH
BE AS DUMB AS A BOX OF ROCKS
BE AS DUMB AS A POST
BE AS GOOD AS ONE'S WORD
BE AS HARD AS NAILS
BE AS SHARP AS A RAZOR
BE AS SHARP AS A TACK
BE AS STRAIGHT AS A DIE
BE AT EACH OTHER'S THROATS
BE AT LOGGERHEADS WITH SB
BE AT SB'S BECK AND CALL
BE AT SB'S MERCY
BE BACK IN ACTION
BE BANG ON
BE BEHIND THE TIMES
BE BOTTOM SHELF
BE BRAIN DEAD
BE CAST IN THE SAME MOULD
BE CHEAP AND CHEERFUL
BE CLEAR AS MUD
BE DEAD ON SB'S FEET
BE DOUBLE-FACED
BE GOOD-FOR-NOTHING
BE GREEN WITH ENVY
BE HEAD AND SHOULDERS ABOVE
BE HIT WITH SB
BE HOPPING MAD
BE IN A JAM
BE IN A PICKLE
BE IN A SPIN
BE IN A STEW
BE IN ONE'S ELEMENT
BE IN STITCHES
BE IN THE BACK BURNER
BE IN THE DRIVING SEAT
BE IN THE PIPELINE
BE IN THE PUBLIC EYE
BE LIKE A GHOST TOWN
BE LIKE APPLES AND ORANGES
BE LIKE CHALK AND CHEESE
BE LIKE TWO PEAS IN A POD
BE NINE DAYS' WONDER
BE NO BIG DEAL
BE OF SERVICE
BE ON SB'S BACK
BE ON SPEAKING TERMS
BE ON THE SAME WAVELENGTH
BE OUT OF ACTION
BE OUT OF ONE'S ELEMENT
BE OVER A BARREL
BE POLAR OPPOSITES
BE POLES APART
BE SB'S CUP OF TEA
BE SB'S FORTE
BE SB'S STRONG SUIT
BE SITTING PRETTY
BE SMOOTH SAILING
BE STREETS AHEAD
BE STUCK IN THE OLD WAYS
BE THE BEST THING SINCE SLICED BREAD
BE THE BLACK SHEEP
BE THE CAT'S WHISKERS
BE THE MIRROR IMAGE OF
BE TOO CLEVER BY HALVES
BE UP TO DATE
BE UP TO SPEED ON
BE UP TO THE MARK
BE UP WITH THE LARK
BE WORLDS APART
BEAR A GRUDGE
BEAR STH IN MIND
BECOME LAW UNTO ONESELF
BEND THE RULES
BETTER SAFE THAN SORRY
BETWEEN THE DEVIL AND THE DEEP BLUE SEA
BIG CHEESE
BIG GUN
BIG NAME
BIG SHOT
BIRDS OF A FEATHER (FLOCK TOGETHER)
BITE THE BULLET
BLOW SMOKE
BLOW STH OUT OF PROPORTION
BREAD-AND-BUTTER
BREATHE FIRE
BRING STH HOME
BUCK NAKED
BUILD BRIDGES
BURN BOATS/BRIDGES
BURST OUT CRYING
BURST OUT LAUGHING
BY FAIR MEANS OR FOUL
BY HOOK OR BY CROOK
BY LEAPS AND BOUNDS
CALL A SPADE A SPADE
CALL IT A DAY
CALL IT QUITS
CALL THE SHOTS
CAN'T HOLD A CANDLE
CARRY THE CAN
CARRY/TAKE STH TO EXTREMES
CATCH SB IN THE ACT
CATCH SB RED-HANDED
CATCH SB WITH THEIR PANTS DOWN
CHANCE SB'S ARM
CHASE ONE'S TAIL
CHICKEN OUT
CHILD'S PLAY
CHOP AND CHANGE
CHOPPED LIVER
CHUFFED TO BITS
CLEAN UP ONE'S ACT
CLEAR THE AIR
CLEVER CLOGS
CLIMB THE WALLS
COME APART AT THE SEAMS
COME HOME TO SB
COME RAIN OR SHINE
COME TO NOTHING
COME TO SB'S RESCUE
COME UP AGAINST A BRICK WALL
COME WHAT MAY
COMMIT STH TO MEMORY
CONNECT THE DOTS
COOK SB'S GOOSE
COOL CALM AND COLLECTED
CROSS SB'S MIND
CROSS THE T'S AND DOT THE I'S
CRY BUCKETS
CUDGEL ONE'S BRAINS
CUSHION THE BLOW
CUT FROM THE SAME CLOTH
DE TROP
DIG SB'S HEELS IN
DISSOLVE INTO LAUGHTER
DISSOLVE INTO TEARS
DO SB A POWER OF GOOD
DO SB A WORLD OF GOOD
DO STH ON A WHIM
DO STH WHEN SB'S BACK IS TURNED
DO STH WITH FLYING COLORS
DO STH WITH ONE ARM TIED BEHIND SB'S BACK
DO THE TRICK
DODGE AND WEAVE
DON'T COUNT SB'S CHICKENS BEFORE THEY HATCH
DRAW A BLANK
DYED-IN-THE-WOOL
EASE THE TENSION
EAT SB'S LUNCH
EVERY TOM DICK AND HARRY
FACE THE MUSIC
FAIL BY THE WAYSIDE
FAINT HEART NEVER WON FAIR LADY
FALL INTO PLACE
FALL OFF THE BACK OF A LORRY
FALL SHORT OF
FEEL AT HOME
FIGHT A LOSING BATTLE
FIGHT SHY OF
FIRST-CLASS
FIRST-RATE
FIT AS A FIDDLE
FLAY SB ALIVE
FOLLOW A DIFFERENT COURSE OF ACTION
FREE REIN
GARDEN VARIETY
GET A PIECE OF THE ACTION
GET AWAY SCOT FREE
GET COLD FEET
GET HEAVY
GET HOLD OF THE WRONG END OF THE STICK
GET IN AT THE GROUND FLOOR
GET IN ON THE ACT
GET ON LIKE A HOUSE ON FIRE
GET SB'S ACT TOGETHER
GET TEARY-EYED
GET THE JITTERS
GET THE PICTURE OF
GET THE SILENT TREATMENT
GET THE UPPER HAND
GET TO GRIPS WITH
GET TO THE BOTTOM OF
GIVE AND TAKE
GIVE GROUND
GIVE IT A SHOT/WHIRL
GIVE IT TO SB STRAIGHT
GIVE SB A LEG UP
GIVE SB THE COLD SHOULDER
GO ABOVE AND BEYOND
GO DOWN IN FLAMES
GO DOWN THE DRAIN
GO DOWN THE PLUGHOLE
GO FROM BAD TO WORSE
GO FROM ONE EXTREME TO ANOTHER
GO FROM STRENGTH TO STRENGTH
GO IN BLIND
GO INTO RAPTURES
GO OFF THE RAILS
GO ONE BETTER
GO PLACES
GO THROUGH THE BACK DOOR
GO TO ANY LENGTHS
GO TO GREAT LENGTHS
GO TO GREAT PAINS
GO TO PIECES
GOLD-PLATED
GOLDEN BOY
GOLDEN MEAN
GRASP/CLUTCH AT STRAWS
GRIN AND BEAR IT
GRIT SB'S TEETH
HALFWAY HOUSE
HANG IN THERE
HAVE A BAD TIME
HAVE A BALL
HAVE A BLAST
HAVE A BONE TO PICK WITH SB
HAVE A CHANGE OF HEART
HAVE A GOOD GOING
HAVE A HEART OF GOLD
HAVE A LOT ON SB'S MIND
HAVE A WHALE OF A TIME
HAVE BUTTERFLIES IN SB'S STOMACH
HAVE ENOUGH ON ONE'S PLATE
HAVE ONE'S HANDS FULL
HAVE ONE'S HEART IN THE RIGHT PLACE
HAVE ONE'S STOMACH IN KNOTS
HAVE SB BY THE BALLS
HAVE SB EATING OUT OF ONE'S HAND
HAVE SB'S EYES ON THE BALL/PRIZE
HAVE SB'S GUTS FOR GARTERS
HAVE SB'S NAME IN THE LIGHTS
HAVE SB'S SAY
HAVE SB/STH IN THE PALM OF ONE'S HAND
HAVE THE BALLS TO DO STH
HAVE THE BRASS
HAVE THE NERVE TO DO STH
HAVE THE TIME OF ONE'S LIFE
HEADS WILL ROLL!
HELL-BENT ON STH
HIGH-PROFILE
HIT IT BIG TIME
HIT THE GROUND RUNNING
HIT THE NAIL ON THE HEAD
HIT THE SACK
HIT-OR-MISS
HOLD SB'S GROUND
HOLD THE REINS
HOLD THE WHIP HAND
HOLD/BEAR A GRUDGE AGAINST
HOPE FOR PATHS TO CROSS
HORSE AROUND
IN A BLINK OF AN EYE
IN HOT WATER
IN ONE'S BIRTHDAY SUIT
IN PIG'S EYE
IN SHORT/MEDIUM/LONG TERM
IN STORE
IN THE BACK OF BEYOND
IN THE BAG
IN THE BUFF
IN THE MIDDLE OF NOWHERE
IN THE RAW
IN THE STICKS
IN THE WORKS
IT'S THE THOUGHT THAT COUNTS
JALL WORK AND NO PLAY MAKES JACK A DULL BOY
JOHN Q. PUBLIC
JUMP ON THE BANDWAGON
JUMP THROUGH HOOPS
JUMP TO CONCLUSIONS
KEEP SB ON A TIGHT REIN
KNOCK STH/SB OUT OF THE PARK
KNOW STH LIKE THE BACK OF SB'S HAND
KNOW STH OFF THE CUFF
LARGER THAN LIFE
LAY DOWN THE LAW
LAY STH AT SB'S DOOR
LEAN OVER BACKWARDS
LEAVE WITHOUT A BACKWARD GLANCE
LIE THROUGH ONE'S TEETH
LIGHTEN THE TONE
LIKE A CAT ON A HOT TIN ROOF
LIKE GREASED LIGHTNING
LIKE PULLING TEETH
LIKE WATCHING PAINT DRY
LIVE UP TO ONE'S EXPECTATIONS
LOOK DAGGERS AT SB
LOSE ONE'S HEAD
LOSE ONE'S TEMPER
LOSE ONE'S WAY
LOUD MOUTH
MAKE A FRESH START
MAKE A GO OF
MAKE A MOUNTAIN OUT OF A MOLEHILL
MAKE A PIG'S EAR OUT OF
MAKE A SPLASH
MAKE ALL THE DIFFEENCE
MAKE AN ELEPHANT OUT OF A FLY
MAKE FUN OF
MAKE IT BIG
MAKE MATTERS WORSE
MAKE PLAIN
MAKE YOURSELF AT HOME
MANY HANDS MAKE LIGHT WORK
MEAN BUSINESS
MEND ONE'S WAYS
MIDDLE GROUND
MIDDLE-OF-THE-ROAD
MIDDLE-OFF-THE-ROAD
MISS THE POINT
MOANING MINNIE
MOVE WITH THE TIMES
MOVER AND SHAKER
MUCH OF A MUCHNESS
NICKEL-AND-DIME
NINE TIMES OUT OF TEN
NITTY-GRITTY
NO GREAT SHAKES
NO HOLDS BARRED
NO-NAME
NOT BE A PATCH ON
NOT THE SHARPEST KNIFE IN THE DRAWER
NOT TO BE A BARREL OF LAUGHS
NOT TO BE IN THE SAME LEAGUE
NOT TO BUDGE AN INCH
NOT TO MINCE WORDS
NOT TO PULL ANY PUNCHES
NOT TO SEE THE FOREST/WOOD FOR THE TREES
NOTHING OUT OF ORDINARY
NOTHING TO WRITE HOME ABOUT
OF DIFFERENT BREED
OFF BASE
OFF BEAM
OFF THE BEATEN TRACK
OFF THE HOOK
OFF THE TOP OF ONE'S HEAD
OIL THE WHEELS
ON A REAL NOTE
ON TENTERHOOKS
ON THE MARK
ON THE RIGHT TRACK
ON THE SPUR OF THE MOMENT
ON THE THRESHOLD OF
ON THE WRONG TRACK
ONE WAY OR ANOTHER
OPEN ONE'S HEART TO SB
OPEN THE FLOODGATES
OUT OF SIGHT OUT OF MIND
OUT OF THE ARK
OVER MY DEAD BODY
OVERSTEP THE MARK
PAINT THE TOWN RED
PASS THE BUCK
PENNY-ANTE
PEOPLE WHO LIVE IN GLASS HOUSES SHOULDN'T THROW STONES
PICK UP THE PIECES
PICK UP THE THREADS
PICTURE-PERFECT
PIE IN THE SKY
PIECE DE RESISTANCE
PIERCE SB'S HEART
PILE ON THE AGONY
PITCH IN TO HELP
PLAY IT SAFE
PLAY SECOND FIDDLE
PLAY SILLY BAGGERS
PLAY THE FIRST FIDDLE
POINT THE FINGER AT SB
POKE FUN AT
POKER FACE
POUR SB'S HEART OUT
PRACTICE MAKES PERFECT
PRE-EMINENT
PULL SB'S CHAIN
PULL SB'S LEG
PULL SB'S SOCKS UP
PULL THE STRINGS
PULL WOOL OVER SB'S EYES
PUSH THE PANIC BUTTON
PUT ON A FA ADE
PUT ON AN ACT
PUT SB'S BACK UP
PUT SB'S FOOT IN IT
PUT SB'S HEART AND SOUL INTO STH
PUT TWO AND TWO TOGETHER
PUT/LEAVE SB IN THE SHADE
QUEER SB'S PITCH
RACK ONE'S BRAIN
RAIN ON SB'S PARADE
RAISE HELL
REST ON ONE'S LAURELS
RIGHT UP SB'S ALLEY/STREET
RISE TO FAME
RISE TO THE OCCASION
ROME WASN'T BUILT IN A DAY
RULE THE ROOST
RUN AROUND IN CIRCLES
RUN-OF-THE-MILL
RUN/GO/WORK LIKE A DREAM
RUN/WORK LIKE CLOCKWORK
SB'S MIND GOES BLANK
SCRATCH SB'S HEAD
SCRATCH/SCRAPE THE SURFACE
SCREW UP ONE'S COURAGE
SEE EYE TO EYE
SEE HOW THE LAND LIES
SET THE BALL ROLLING
SET THE BAR HIGH
SET THE BAR LOW
SET THE WHEELS IN MOTION
SHED A TEAR
SHED LIGHT ON
SHIFT SB'S GROUND
SHOOT A LINE
SHOOT FROM THE HIP
SILENT AS THE DEAD
SILENT AS THE GRAVE
SKY IS THE LIMIT
SLIP SB'S MIND
SLIP THROUGH THE NET
SMALL FRY
SPARK SB'S INTEREST
SPEAK ONE'S MIND
SPOT ON
STAB SB IN THE BACK
STAND ONE'S GROUND
STAND OUT FROM THE CROWD
STAND/HOLD FAST
START FROM SCRATCH
STICK OUT LIKE A SORE THUMB
STICK TO SB'S GUNS
STRIKE A CHORD
STUBBORN AS A MULE
STUCK IN A RUT
SUGAR THE PILL
SURROUNDED BY THE GREEN BELT
SWEETEN THE PILL
SWING INTO ACTION
TAKE A STROLL DOWN THE MEMORY LANE
TAKE A TURN FOR THE BETTER
TAKE A TURN FOR THE WORSE
TAKE ONE'S TIME TO DO STH
TAKE STH BY THE THROAT
TAKE STOCK OF
TAKE THE BLAME
TAKE THE FALL FOR SB
TAKE THE LAW INTO ONE'S OWN HANDS
TAKE THE LUMPS
TAKE THE MICKEY OUT OF SB
TAKE THE STING OUT OF
THE ANSWER TO MY PRAYERS
THE BULL'S EYE
THE CHERRY ON TOP
THE EARLY BIRD CATCHES THE WORM
THE FLOWER OF
THE GRASS IS ALWAYS GREENER ON THE OTHER SIDE
THE HEART OF THE MATTER
THE INS AND OUTS OF STH
THE JEWEL IN THE CROWN
THE LIFE AND SOUL OF THE PARTY
THE NAME OF THE GAME
THE NUTS AND BOLTS
THE SCUM OF THE EARTH
THE TIP OF THE ICEBERG
THE WORLD IS SB'S OYSTER
THROW A SPANNER IN THE WORKS
THROW A WOBBLY
THROW DUST IN SB'S EYES
THROW IN THE TOWEL
THROW ONE'S WEIGHT AROUND
THROW SOMEONE FOR A LOOP
THROW THE BOOK AT SB
TIE UP A FEW LOOSE ENDS
TOO MANY COOKS SPOIL THE BROTH
TOP DRAWER
TOP NOTCH
TOUR DE FORCE
TRIAL AND ERROR
TURN ON THE WATERWORKS
TURN OVER A NEW LEAF
UP THE CREEK
UP TO ONE'S NECK IN
UPPER ECHELON
UPSET THE APPLE CART
VICIOUS CYCLE/CIRCLE
VOICE ONE'S CONCERN
VOLTE-FACE
WATCH THIS SPACE
WAVE A MAGIC WAND
WEAR SB'S HEART ON SB'S SLEEVE
WET BLANKET
WHAT'S DONE IS DONE
WHEN ALL IS SAID AND DONE
WHEN HELL FREEZES OVER
WHILE THE CAT'S AWAY THE MICE WILL PLAY
WIDE OFF THE MARK
WILLY NILLY
WITH BATED BREATH
WORK AGAINST THE CLOCK
WORK AT CROSS-PURPOSES
WORK LIKE A CHARM
WORK LIKE MAGIC
WORK/DO WONDERS
YOU SCRATCH MY BACK AND I'LL SCRATCH YOURS
YOU SNOOZE, YOU LOSE
PUT ON A GOOD SHOW
UP TO ONE'S EYES/EYEBALLS IN
TO BE AT SB'S WITS END
TO GRASP THE NETTLE
IN THE AIR
STATE OF THE ART
OUT OF BLINK
A GUTLESS WONDER
MOVE MOUNTAINS
UNDER THE WEATHER
DEAD TIRED
LEAVE SB TO ONE'S OWN DEVICES
A DOODLE
THE NEXT BEST THING
GRASP THE NETTLE
ICING OF THE CAKE
AT THE BREAK OF DAWN
RATEPAYER
ETCH STH IN SB'S MEMORY
ON TOP OF THE WORLD
TO RUFFLE SB'S FEATHERS
OPEN THE DOOR TO
PUBLIC
TO COME IN FOR BLAME
AS BUSY AS A BEE
TO HAVE A BRAINWAVE
GO IN ONE AR AND OUT THE OTHER
RUN RINGS AROUND
GET SB'S FINGER OUT
A KNOWN QUANTITY
TO LEARN STH BY HEART
GET THE DRIFT OF
BE AS FUNNY AS A BARREL OF MONKEYS
COUCH POTATO
LEAD SB ON A GOOSE CHASE
TO HIT A SNAG
THIRD ESTATE
FULL OF THE MILK OF HUMAN KINDNESS
THE MORE THE MERRIER
AT SB'S WITS END
KNOW SB'S STUFF
WITHOUT A SHADOW OF A DOUBT
NIGH IMPOSSIBLE
AT SEA
IN A TIGHT CORNER
TO DRAG SB'S HEELS
COMMON GROUND
LIKE FINDING A NEEDLE IN A HAYSTACK
SHOOT THE BREEZE
IN A FLASH
A FAIR CRACK AT THE WHIP
OFF COLOR
AT A MOMENT'S NOTICE
LIKE GETTING BLOOD OUT FROM A STONE
IN SB'S MIND'S EYE
COME IN FOR BLAME
ON THE NOSE
NOT TO SLEEP A WINK
LEARN STH BY HEART
WRAP ONE'S HEAD AROUND
SIT ON THE FENCE
A PAIN IN THE NECK/ARSE
COME HELL OR HIGH WATER
OPEN THE WAY FOR
AT SB'S WIT END
TO BURN THE CANDLE AT BOTH ENDS
OUT OF LINE
SOFT SPOT
CR?ME DE LA CR?ME
DOWNCAST
FOREGONE CONCLUSION
PULL SB'S WEIGHT
TO SET THE WORLD ON FIRE
A PET HATE
SLOG AWAY
OUT OF DATE
TO GET THE PICTURE/MESSAGE
IN THE SPOTLIGHT
CREAM OF THE CROP
KNOW STH INSIDE OUT
IN NO TIME AT ALL
NOT KNOW BEANS ABOUT
LEARN STH BY HEART/ROTE
TO BE FOAMING AT THE MOUTH
OUT-DATED
TO OPEN THE WAY FOR
NOLENS VOLENS
SEE HOW THE LAND LIES
DUMB AS A BOX OF A DIPSTICK
DOG-TIRED
RUN CIRCLES ROUND
TO BEAT AROUND THE BUSH
FIND OUT THE TRUTH
HAVE SB'S BACK AGAINST THE WALL
IN A STATE OF NERVES
AS SURE AS DAY
EASY AS A PIE
GROUND-BREAKING
TO FLY OFF THE HANDLE
LEAVE SB TO THEIR OWN DEVICES
TO GET CHOKED UP
TO GET THE DRIFT OF
TO WRAP ONE'S HEAD AROUND
AT THE EDGE OF SB'S SEAT
NOT TO KNOW BEANS ABOUT
TO DRIVE SB UP THE WALL
GO IN ONE EAR AND OUT THE OTHER
PRIME EXAMPLE OF
AS PLAIN AS THE NOSE ON SB'S FACE
SET THE WORLD ON FIRE
TO RUN RINGS AROUND
WITHOUT A SECOND THOUGHT
HAVE STH ON THE BRAIN
HOI POLLOI
SPRING TO SB'S MIND
SILVER LINING
BE IN FULL SWING
IN A HEARTBEAT
TO BE ON ONE'S LAST LEG
TO FALL AT THE SEAMS
A ROUGH RIDE
STUCK IN ONE'S OLD WAYS
TO BE SHITTING BRICKS
TAILOR-MADE
THROW A TANTRUM/FIT
EASY AS PIE
THE GREAT UNWASHED
LAYPERSON
CHATTERBOX
SPREAD ONESELF TOO THIN
EASE AS PISSING
TO ADD FIRE TO THE FIRE
TO HAVE A GO AT
TO BURN THE MIDNIGHT OIL
AN APPLE A DAY KEEPS THE DOCTOR AWAY
TO KNOW ZIP ABOUT STH
CHEW THE FAT
MAKER AND SHAKER
LEARN THE TRUTH
FLY OFF THE HANDLE
BEAT AROUND THE BUSH
FIGHT TOOTH AND NAIL
TO LOSE TRUST
TAKE ACCOUNT OF
TAXPAYER
TO MOVE MOUNTAINS
TO BE SITTING ON THE FENCE
TICKLED PINK
BE IN THE SPOTLIGHT
GIVEN FREE REIN TO
FOOL'S PARADISE
TO GET SB'S FINGER OUT
TO GET A MOVE ON
A NIGH IMPOSSIBLE
OVER THE TOP
SB'S AVERAGE BEAR
HAPPY-GO-LUCKY
TO THROW A TANTRUM
OUT OF GAS
GO DOWNHILL
THROW CAUTION TO THE WIND
A STATE OF NERVES
ONCE IN A BLUE MOON
GET THE MESSAGE/ PICTURE
PAR EXCELLENCE
TO SEE RED
SEARCH ME
TO RUB SB THE WRONG WAY
A TALL ORDER
TO BE A HARD GOING
AS EASY AS PIE
RUN THE RISK OF
TO TAKE THE WORLD BY STORM
TO WIPE THE SLATE CLEAN
TO BLOW A FUSE
A FOREGONE CONCLUSION
A SLAP ON THE WRIST
MAGNUM OPUS
NOT MINCE WORDS
TO PUT FINISHING TOUCHES
IN A TIGHT SPOT
TO BE SNOWED UNDER
TO BE NIGH IMPOSSIBLE
TO AS RARE AS HEN'S TEETH
HEDGE ONE'S BETS
ALL OVER THE PLACE
A SOFT SPOT
TEN TO THE PENNY
LEARN STH BY ROTE
IN THE VANGUARD
OVER THE MOON
COME TO LIGHT
BACK IN THE GAME
OUT OF ELEMENT
TO CALL IT QUITS
SHOW ONE'S TRUE COLOURS
ONCE IN A LIFETIME
CREATURE COMFORT
TO BE AT A LOSS FOR WORDS
ON CLOUD NINE
BURN THE MIDNIGHT OIL
CREATURE COMFORTS
ETCHED IN SB'S MEMORY
SLOW ON THE UPTAKE
JOG SB'S MEMORY
A BAD WORKMAN BLAMES SB'S TOOLS
BETAKE ACCOUNT OF
KEEP SB ON A SHORT LEASH
OUT OF THIS WORLD
PET HATE
TO GO BACK TO THE DRAWING BOARD
TO BE ON THE RUN
TO FEEL THE BLUES
TO MESS WITH SOMEONE'S HEAD
TO PUT FINISHING TOUCHES ON
TALK TURKEY
TO MAKE CRYSTAL CLEAR
DOWN IN THE DUMPS
TO GET HOLD OF THE WRONG TREE
STATE-OF-THE-ART
LIKE WATER AND OIL
PLUCK UP THE COURAGE
TALL ORDER
THROW A FIT
BOG-STANDARD
PET PEEVE
BE ON THE SAFE SIDE
JOG ONE'S MEMORY
PROS AND CONS
TO PULL SB'S WEIGHT
BE NIGH IMPOSSIBLE
TO PLUCK UP THE COURAGE
ON AND OFF
DOWN-TO-EARTH
A TOUGH NUT TO CRACK
GO THROUGH THE MOTIONS
TO BE ONLY A MATTER OF TIME
TO DIG YOURSELF INTO A HOLE
GOOF AROUND
TO BE AT THE EDGE OF SB'S SEAT
TO KNOW STH INSIDE OUT
AT THE END OF THE DAY
HIT THE HAY
A TIGHT SPOT
CR?ME DE LE CR?ME
FINDING A NEEDLE IN A HAYSTACK
A QUANTUM LEAP
LAZY BONES
TO COME TO TERMS WITH
ETCHED INTO SB'S MEMORY
AT A SNAIL'S PACE
TO BE ON THE NOSE
IN SEVENTH HEAVEN
GIVE IT A BASH
A DODDLE
PLAIN SAILING
GO OVERBOARD
TO KNOW ZIP ABOUT
IF MY MEMORY SERVES ME RIGHT
DONKEY'S YEARS
NOT CUT IT
A KNIGHT ON A WHITE HORSE
A DOUBLE-EDGED SWORD
KNOW SB'S ONIONS
A COUCH POTATO
TO BE OVER SB'S HEADS
TO LET ONE'S HAIR DOWN
NOT BE CLEAR TO SB
UP IN THE AIR
WORRYWART
TO SIT ON A FENCE
TO BE A WORRYWART`.split("\n");